language: julia
os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - export DOCUMENTER_DEBUG="true"
        - julia --color=yes --project=docs/ -e 'using Pkg;
                                                Pkg.instantiate();
                                                Pkg.develop(PackageSpec(path=pwd()));
                                                Pkg.build()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
    - stage: "Coverage"
      julia: 1.0
      os: linux
      after_success: # Intentionally rerun tests
        - julia -e 'using Pkg; Pkg.add("Coverage")'
        - julia -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'
        - julia -e 'using Coverage; Codecov.submit(Codecov.process_folder())'
